/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'ncrash' at '13. 11. 14 오전 8:44' with Gradle 1.8
 *
 * @author ncrash, @date 13. 11. 14 오전 8:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
